spring:
  application:
    name: bank_notification_service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: bank_notification_service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.notification.event.TransferEvent

server:
  port: 8081

logging:
  level:
    com.example.notification: DEBUG
    org.springframework.kafka: INFO
